In [1]:
import numpy as np 
import pandas as pd

In [2]:
np.random.seed(123)

N = 1000
J = 4
T = 50

# Generate the data
np.random.seed(123)
mu = np.array([-1.71, 0.44, -1.37, -0.91, -1.23]).reshape(-1, 1)
sigma = np.diag(np.array([3.22, 3.24, 2.87, 4.15, 1.38])).reshape(5, 5)
print(mu, '\n')
print(sigma)


# generate the random parameters
betas = np.random.multivariate_normal(mu.flatten(), sigma, N)
print(betas.shape)

[[-1.71]
 [ 0.44]
 [-1.37]
 [-0.91]
 [-1.23]] 

[[3.22 0.   0.   0.   0.  ]
 [0.   3.24 0.   0.   0.  ]
 [0.   0.   2.87 0.   0.  ]
 [0.   0.   0.   4.15 0.  ]
 [0.   0.   0.   0.   1.38]]
(1000, 5)


In [3]:
price_transition_states = pd.read_csv(r'price_transition_states.csv')
price_transition_matrix = pd.read_csv(r'transition_prob_matrix.csv')

print(price_transition_states.head())
print(price_transition_matrix.head())

         X1        X2        X3        X4  X5  id
0  0.809830  2.730574  0.770491  2.966650   0   1
1  0.785441  2.453663  0.771422  2.964841   0   2
2  0.823926  2.238301  0.790901  2.914317   0   3
3  1.005571  1.581941  0.918171  2.084867   0   4
4  0.798525  2.693030  0.762935  2.690978   0   5
         V1        V2        V3        V4        V5        V6        V7  \
0  0.050283  0.020251  0.017505  0.003655  0.026568  0.006548  0.006352   
1  0.040564  0.023169  0.016224  0.003816  0.024936  0.007435  0.007776   
2  0.034444  0.016302  0.015208  0.004359  0.022437  0.006756  0.007631   
3  0.017591  0.008223  0.009868  0.007142  0.013897  0.006043  0.011003   
4  0.042309  0.016379  0.015619  0.003890  0.027125  0.006523  0.006811   

         V8        V9       V10  ...       V91       V92       V93       V94  \
0  0.008375  0.016022  0.013590  ...  0.017482  0.003807  0.008912  0.005710   
1  0.006751  0.014843  0.012902  ...  0.020574  0.003186  0.010063  0.005734   
2  0.0084

In [4]:
price_transition_states

X1        X2        X3        X4  X5   id
0   0.809830  2.730574  0.770491  2.966650   0    1
1   0.785441  2.453663  0.771422  2.964841   0    2
2   0.823926  2.238301  0.790901  2.914317   0    3
3   1.005571  1.581941  0.918171  2.084867   0    4
4   0.798525  2.693030  0.762935  2.690978   0    5
..       ...       ...       ...       ...  ..  ...
95  1.096901  2.540894  0.933728  2.026588   0   96
96  1.228067  1.985250  0.941085  2.525047   0   97
97  1.118906  3.728712  1.055625  2.475710   0   98
98  0.847625  2.102348  1.363938  1.771260   0   99
99  0.761153  1.718405  0.852639  1.856784   0  100

[100 rows x 6 columns]

In [5]:
price_transition_matrix

V1        V2        V3        V4        V5        V6        V7  \
0   0.050283  0.020251  0.017505  0.003655  0.026568  0.006548  0.006352   
1   0.040564  0.023169  0.016224  0.003816  0.024936  0.007435  0.007776   
2   0.034444  0.016302  0.015208  0.004359  0.022437  0.006756  0.007631   
3   0.017591  0.008223  0.009868  0.007142  0.013897  0.006043  0.011003   
4   0.042309  0.016379  0.015619  0.003890  0.027125  0.006523  0.006811   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.022406  0.010178  0.011546  0.005559  0.015755  0.005905  0.007434   
96  0.014125  0.006274  0.008583  0.005706  0.010867  0.005148  0.006759   
97  0.013230  0.006321  0.007653  0.004281  0.010171  0.004477  0.006573   
98  0.016398  0.007619  0.009392  0.006894  0.012828  0.006098  0.009410   
99  0.013686  0.007597  0.008115  0.007995  0.012092  0.005991  0.017418   

          V8        V9       V10  ...       V91       V92       V93       V94  \
0   0.008375  0.016022  0.013590  ...  0.017482  0.003807  0.008912  0.005710   
1   0.006751  0.014843  0.012902  ...  0.020574  0.003186  0.010063  0.005734   
2   0.008431  0.019615  0.015308  ...  0.016124  0.004657  0.010655  0.004589   
3   0.009424  0.022074  0.012562  ...  0.010919  0.007949  0.013787  0.002806   
4   0.008304  0.017501  0.014749  ...  0.016193  0.004160  0.009280  0.004994   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.010891  0.027838  0.015147  ...  0.010508  0.008855  0.010696  0.003277   
96  0.012477  0.030100  0.013551  ...  0.007031  0.013129  0.010076  0.002364   
97  0.022304  0.023152  0.009947  ...  0.007212  0.014083  0.006911  0.002808   
98  0.009549  0.022639  0.012384  ...  0.010010  0.010943  0.011931  0.002618   
99  0.003487  0.013291  0.008660  ...  0.012523  0.003063  0.016260  0.002462   

         V95       V96       V97       V98       V99      V100  
0   0.016266  0.008533  0.006934  0.002275  0.001474  0.008172  
1   0.013634  0.008189  0.006430  0.001822  0.001520  0.009950  
2   0.014261  0.009842  0.009434  0.002486  0.001853  0.009703  
3   0.011120  0.011316  0.016923  0.003837  0.003444  0.015517  
4   0.017674  0.008824  0.008212  0.002280  0.001601  0.008316  
..       ...       ...       ...       ...       ...       ...  
95  0.013045  0.012874  0.017172  0.004015  0.003121  0.010308  
96  0.012457  0.014006  0.033324  0.005777  0.003969  0.009970  
97  0.011422  0.010620  0.013875  0.008872  0.003258  0.008857  
98  0.011045  0.012419  0.017758  0.004460  0.005623  0.013918  
99  0.007017  0.007676  0.009589  0.001575  0.002257  0.032084  

[100 rows x 100 columns]

In [8]:
price_transition_matrix_np = price_transition_matrix.to_numpy()
price_transition_states_np = price_transition_states.to_numpy()

In [78]:
def simulate_prices(states, transition, T):
    state_indices = np.arange(states.shape[0])
    price_simu = np.zeros((T, 6))
    price_simu[0] = states[0]
    for t in range(1, T):
        preceding_state = price_simu[t-1, :]
        index_preceding_state = int(preceding_state[-1] - 1)
        index_next_state = np.random.choice(state_indices, p=(transition[index_preceding_state, :].flatten()))
        price_simu[t, :] = states[index_next_state]
    return price_simu


In [80]:
pd.DataFrame(simulate_prices(price_transition_states_np, price_transition_matrix_np, 50))

0         1         2         3    4      5
0   0.809830  2.730574  0.770491  2.966650  0.0    1.0
1   1.218058  2.715940  1.226585  2.843296  0.0   55.0
2   0.767428  2.389803  0.735096  3.285335  0.0   38.0
3   0.996853  2.545602  0.754341  2.535837  0.0   40.0
4   1.008565  2.552367  0.989916  2.501819  0.0    9.0
5   1.008565  2.552367  0.989916  2.501819  0.0    9.0
6   0.731230  2.406947  0.725722  2.049882  0.0   91.0
7   0.802718  1.284147  0.827039  1.712204  0.0   15.0
8   0.977670  2.013828  0.868063  1.641846  0.0   80.0
9   0.996847  2.052179  0.915427  2.745875  0.0   68.0
10  1.067601  2.276084  0.911903  2.492078  0.0   44.0
11  0.637916  1.979651  0.645896  1.981934  0.0   21.0
12  0.798525  2.693030  0.762935  2.690978  0.0    5.0
13  0.600625  1.985493  0.641010  2.542885  0.0   84.0
14  0.970094  2.338620  1.045266  3.034404  0.0   61.0
15  0.850255  2.550520  0.780800  2.290278  0.0   19.0
16  1.005571  1.581941  0.918171  2.084867  0.0    4.0
17  1.168815  3.006654  1.286853  3.208121  0.0   92.0
18  1.021932  3.241943  1.011577  2.956740  0.0   28.0
19  0.992057  2.609810  0.960403  3.004935  0.0   27.0
20  0.771803  2.250362  0.724182  2.396910  0.0   58.0
21  0.791902  1.943744  0.781021  2.019423  0.0   48.0
22  1.025595  2.033337  0.950818  2.153375  0.0   24.0
23  0.637916  1.979651  0.645896  1.981934  0.0   21.0
24  0.972732  1.989758  1.053143  3.589961  0.0   85.0
25  1.021932  3.241943  1.011577  2.956740  0.0   28.0
26  1.017380  3.387785  0.931056  3.555434  0.0    8.0
27  0.771803  2.250362  0.724182  2.396910  0.0   58.0
28  0.600625  1.985493  0.641010  2.542885  0.0   84.0
29  1.005571  1.581941  0.918171  2.084867  0.0    4.0
30  0.955688  1.607947  0.844384  2.667512  0.0   18.0
31  0.585977  1.760731  0.627328  1.987726  0.0   20.0
32  0.771803  2.250362  0.724182  2.396910  0.0   58.0
33  0.992057  2.609810  0.960403  3.004935  0.0   27.0
34  0.972732  1.989758  1.053143  3.589961  0.0   85.0
35  0.950566  2.493155  0.915474  3.637841  0.0   25.0
36  1.172667  3.612419  1.062067  4.063881  0.0   52.0
37  1.017380  3.387785  0.931056  3.555434  0.0    8.0
38  0.937506  2.515288  0.778170  2.950657  0.0   76.0
39  0.761153  1.718405  0.852639  1.856784  0.0  100.0
40  0.606032  1.761290  0.610645  2.384826  0.0   60.0
41  0.805124  2.822263  0.788838  2.360375  0.0   56.0
42  0.950566  2.493155  0.915474  3.637841  0.0   25.0
43  0.628051  1.588169  0.662635  2.246497  0.0   71.0
44  0.582541  1.670523  0.600641  1.809599  0.0   46.0
45  0.585977  1.760731  0.627328  1.987726  0.0   20.0
46  0.606032  1.761290  0.610645  2.384826  0.0   60.0
47  0.669883  1.559776  0.668380  1.967928  0.0   49.0
48  0.731230  2.406947  0.725722  2.049882  0.0   91.0
49  1.067601  2.276084  0.911903  2.492078  0.0   44.0

In [81]:
betas

array([[-1.20221324,  2.2352218 , -3.92182507, -3.12159768, -1.9097014 ],
       [-2.4796562 , -3.92802264,  0.77463203,  2.454232  , -2.24818943],
       [ 0.966203  ,  0.26952386, -2.45236862, -2.29299624, -1.75156071],
       ...,
       [ 0.12070823,  1.76831485,  0.30918328, -4.03389818, -0.45198806],
       [-5.13770196,  2.15692738, -0.05122573, -3.02997822, -2.47279716],
       [-5.04713952, -2.11354815,  0.17811297, -3.19623874, -2.82040162]],
      shape=(1000, 5))